6-sign
piybeep/sirin-s pull request #12
Opened 2022-12-23 17:21 UTC by ChocolateHokage

в 6-sign два коммита, актуальный sign

2022-12-26 09:12 UTC, danyatochkaru requested changes
ты зачем половину проекта удалить решил?

2022-12-26 09:12 UTC, danyatochkaru commented on Dockerfile
> +<<<<<<< HEAD
исправь конфликт

2022-12-26 09:12 UTC, danyatochkaru commented on src/session/session.controller.ts
> +    // const valid_user = this.sessionService.validateUser(user)
если это не нужно, удаляй

2022-12-26 09:12 UTC, danyatochkaru commented on src/session/session.service.ts
> +    if (!(await bcrypt.compare(dto.password, user.token))) throw new UnauthorizedException('invalid password')
поменяй сообщение ошибки на `
Логин или пароль неправильные
`

2022-12-26 09:12 UTC, danyatochkaru commented on src/session/session.service.ts
> +    if (!user) throw new BadRequestException('No such user')
и тут как ниже. нельзя на клиент отправлять что именно неправильно

2022-12-26 09:12 UTC, danyatochkaru commented on src/session/strategies/local-auth.guard.ts
> +        // console.log(context.);
почисть

2022-12-26 09:12 UTC, danyatochkaru commented on src/session/strategies/local.strategy.ts
> +        if (!user) throw new UnauthorizedException('No such user')
меняй

2022-12-26 09:12 UTC, danyatochkaru commented on src/sessions/sessions.module.ts
> +import { TypeOrmModule } from '@nestjs/typeorm/dist/typeorm.module';
мужик ты чего?

2022-12-26 09:12 UTC, danyatochkaru commented on src/sessions/sessions.service.ts
> +            throw new ForbiddenException('Access Denied1');
что за цифры? убирай или  в скобках пиши

2022-12-26 12:53 UTC, danyatochkaru requested changes

2022-12-26 12:53 UTC, danyatochkaru commented on Dockerfile
> +COPY /*.json ./
а оно работает так? может `./*.json`?

2022-12-26 12:53 UTC, danyatochkaru commented on src/sessions/sessions.service.ts
> +        let aa
аа?

2022-12-26 12:53 UTC, danyatochkaru commented on src/sessions/sessions.service.ts
> +        return
void или ты забыл указать что она возвращает? если первое, то return в конце не нужен

2022-12-26 12:54 UTC, ChocolateHokage commented on src/sessions/sessions.service.ts
> +        let aa
ахахахх

2022-12-26 15:16 UTC, ChocolateHokage commented on Dockerfile
> +COPY /*.json ./
работает

2022-12-26 16:14 UTC, danyatochkaru commented on src/sessions/sessions.service.ts
> +            throw new HttpException(errorResponse, HttpStatus.UNPROCESSABLE_ENTITY)
к чему тут `UNPROCESSABLE_ENTITY`? мне кажется это не совсем корректным

2022-12-27 11:11 UTC, danyatochkaru approved these changes

2022-12-27 11:11 UTC, merged