3-reviews
piybeep/sirin-s pull request #9
Opened 2022-12-15 09:15 UTC by ChocolateHokage

2022-12-15 09:16 UTC, ChocolateHokage commented
30 min

2022-12-15 10:02 UTC, danyatochkaru requested changes

2022-12-15 10:02 UTC, danyatochkaru commented on src/reviews/reviews.service.ts
> +        if (start < 0 || count < 0){
а как ты строку с числом сравнивать собрался? приводи к общему типу и сравнивай

2022-12-16 09:31 UTC, danyatochkaru approved these changes

2022-12-16 09:31 UTC, merged